name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch to run the action on'
        required: true
        default: 'feature-branch'  # Replace with your feature branch name

jobs:
  run-on-feature-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchName }}

    # Add your job steps here
    - name: Example Step
      run: echo "Running on ${{ github.event.inputs.branchName }}"